### ISSUE TITLE
create a tag

### ISSUE THREAD

**Issue by tacaswell** [dectris/HDF5Plugin#2]
Would it be possible to add a tag to this repository?  At NSLS-II we are packaging this for conda (python centric package manager) and it would be nice to target a tag rather than a commit SHA.

https://github.com/conda-forge/staged-recipes/pull/669

**Comment by eugenwintersberger** [comment]
@tascwell This repository is no longer maintained. If you want to contribute to the HDF5 filter plugins please use the https://github.com/nexusformat/HDF5-External-Filter-Plugins repository.

**Comment by tacaswell** [comment]
attn @brunoseivam

@eugenwintersberger Can you please add a README to this repo that states that and redirects to the nexusformat repo?  Might also be a good idea to disable issues.

Can you also update https://www.hdfgroup.org/services/filters.html to point to the correct canonical source?

**Comment by eugenwintersberger** [comment]
@tacaswell I just contacted the developer at DECTRIS who is currently the administrator for this repository. I hope I can get all your suggestions done until Monday. I also contacted the HDF group to update the link on their site.

**Comment by tacaswell** [comment]
Thanks! :beers:

**Comment by eugenwintersberger** [comment]
Btw. Thanks for your contributions. I hope I will see you soon on the new official repository ;)
